### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by danieroux** [luite/hfsevents#7]
```
error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
```

Result of:

```
cabal-dev install -v3 hfsevents > hfsevents-fail.log
```

Linked: https://gist.github.com/danieroux/8171993

**Comment by ryandesign** [comment]
The MacPorts prefix is /opt/local. /usr/pkg does not normally exist on OS X.

**Comment by danieroux** [comment]
This is probably unreproducible by now
