### ISSUE TITLE
Build error on Yosemite 

### ISSUE THREAD

**Issue by dikmax** [luite/hfsevents#9]
Here's output.

```
[1 of 1] Compiling System.OSX.FSEvents ( System/OSX/FSEvents.hs, dist/build/System/OSX/FSEvents.o )

In file included from /usr/include/os/object.h:75:0:
    0,
                     from /usr/include/dispatch/dispatch.h:48,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                     from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19,
                     from cbits/c_fsevents.m:1:

/usr/include/objc/NSObject.h:22:1:
     error: unknown type name 'instancetype'
     - (instancetype)self;
     ^

/usr/include/objc/NSObject.h:36:1:
     error: unknown type name 'instancetype'
     - (instancetype)retain OBJC_ARC_UNAVAILABLE;
     ^

/usr/include/objc/NSObject.h:38:1:
     error: unknown type name 'instancetype'
     - (instancetype)autorelease OBJC_ARC_UNAVAILABLE;
     ^

/usr/include/objc/NSObject.h:60:1:
     error: unknown type name 'instancetype'
     - (instancetype)init;
     ^

/usr/include/objc/NSObject.h:62:1:
     error: unknown type name 'instancetype'
     + (instancetype)new;
     ^

/usr/include/objc/NSObject.h:63:1:
     error: unknown type name 'instancetype'
     + (instancetype)allocWithZone:(struct _NSZone *)zone;
     ^

/usr/include/objc/NSObject.h:64:1:
     error: unknown type name 'instancetype'
     + (instancetype)alloc;
     ^

In file included from /usr/include/dispatch/dispatch.h:51:0:
    0,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                     from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19,
                     from cbits/c_fsevents.m:1:

/usr/include/dispatch/object.h:143:15:
     error: expected identifier or '(' before '^' token
     typedef void (^dispatch_block_t)(void);
                   ^

/usr/include/dispatch/object.h:362:3:
     error: unknown type name 'dispatch_block_t'
       dispatch_block_t notification_block);
       ^
cbits/c_fsevents.m: In function 'osVersion':

cbits/c_fsevents.m:106:4:
     warning: 'Gestalt' is deprecated (declared at /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Gestalt.h:123) [-Wdeprecated-declarations]
        Gestalt(gestaltSystemVersionMajor, majorVersion);
        ^

cbits/c_fsevents.m:107:4:
     warning: 'Gestalt' is deprecated (declared at /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Gestalt.h:123) [-Wdeprecated-declarations]
        Gestalt(gestaltSystemVersionMinor, minorVersion);
        ^

cbits/c_fsevents.m:108:4:
     warning: 'Gestalt' is deprecated (declared at /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Gestalt.h:123) [-Wdeprecated-declarations]
        Gestalt(gestaltSystemVersionBugFix, bugFixVersion);
        ^
Failed to install hfsevents-0.1.5
cabal: Error: some packages failed to install:
hfsevents-0.1.5 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by DNNX** [comment]
I've installed haskell-platform through `brew cask install` and I'm seeing the same problem when I try and run `cabal install hfsevents==0.1.5`. Trying ghcformacosx.github.io now, let's see if it works.

**Comment by luite** [comment]
what GHC were you using before? I wonder if we can detect this problem, and either pass additional options to `gcc` to make it accept the yosemite headers or at least print a reasonable error message pointing the user into the right direction.

**Comment by DNNX** [comment]
It was 7.8.3, the same as the one I have now.

**Comment by luite** [comment]
How did you install the old one?

**Comment by DNNX** [comment]
brew cask install haskell-platform , IIRC

**Comment by bjm88** [comment]
Thanks guys.  I did brew install ghc and cabal.....I have ghc 7.8.3......we are in the process of upgrading from Ruby 1.9 and Rails 3.2.17 to Ruby 2.1 and Rails 3.2.23......hitting a lot of similar issues.....again landed on this Cairo compile error doing gem install cairo.....

Any ideas this time...its a different compile issue...

Ben$ gem install cairo
Building native extensions.  This could take a while...
ERROR:  Error installing cairo:
	ERROR: Failed to build gem native extension.

    /Users/Ben/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150331-3135-1cof2ow.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
checking for Mac OS X... yes
checking for HAVE_RUBY_ST_H in ruby.h... yes
checking for HAVE_RUBY_IO_H in ruby.h... yes
checking for rb_errinfo() in ruby.h... yes
checking for enum ruby_value_type in ruby.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rb_cairo.c
compiling rb_cairo_constants.c
compiling rb_cairo_context.c
compiling rb_cairo_device.c
compiling rb_cairo_exception.c
compiling rb_cairo_font_extents.c
compiling rb_cairo_font_face.c
compiling rb_cairo_font_options.c
compiling rb_cairo_glyph.c
compiling rb_cairo_io.c
compiling rb_cairo_matrix.c
compiling rb_cairo_path.c
compiling rb_cairo_pattern.c
compiling rb_cairo_private.c
compiling rb_cairo_rectangle.c
compiling rb_cairo_region.c
compiling rb_cairo_scaled_font.c
compiling rb_cairo_surface.c
In file included from /usr/include/dispatch/dispatch.h:51:0,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23,
                 from /opt/local/include/cairo/cairo-quartz.h:43,
                 from rb_cairo_surface.c:54:
/usr/include/dispatch/object.h:143:15: error: expected identifier or '(' before '^' token
 typedef void (^dispatch_block_t)(void);
               ^
/usr/include/dispatch/object.h:362:3: error: unknown type name 'dispatch_block_t'
   dispatch_block_t notification_block);
   ^
In file included from /usr/include/Availability.h:151:0,
                 from /usr/include/stdio.h:65,
                 from /opt/local/include/cairo/cairo-ps.h:44,
                 from rb_cairo.h:23,
                 from rb_cairo_surface.c:14:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:279:36: error: expected ',' or '}' before '__attribute__'
   kFSEventStreamCreateFlagMarkSelf __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0) = 0x00000020
                                    ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:480:35: error: expected ',' or '}' before '__attribute__'
   kFSEventStreamEventFlagOwnEvent __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0) = 0x00080000
                                   ^
rb_cairo_surface.c: In function 'cr_quartz_surface_initialize':
rb_cairo_surface.c:1283:31: warning: assignment makes pointer from integer without a cast [enabled by default]
                   objc_object = NUM2ULONG (rb_objc_pointer);
                               ^
make: *** [rb_cairo_surface.o] Error 1

make failed, exit code 2

**Comment by bjm88** [comment]
So if I switch between gcc 4.8 via mac ports and Apple's bundled gcc I get different behavior.  I can install cairo with Apples....however other libraries have problems that require gcc 4.4+ that Apple didn't update...catch 22....

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin14/4.8.4/lto-wrapper
Target: x86_64-apple-darwin14
Configured with: /opt/local/var/macports/build/_opt_mports_dports_lang_gcc48/gcc48/work/gcc-4.8.4/configure --prefix=/opt/local --build=x86_64-apple-darwin14 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc48 --includedir=/opt/local/include/gcc48 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-4.8 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.8 --with-gxx-include-dir=/opt/local/include/gcc48/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --disable-isl-version-check --with-cloog=/opt/local --disable-cloog-version-check --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc48 4.8.4_0'
Thread model: posix
gcc version 4.8.4 (MacPorts gcc48 4.8.4_0) 

vs

gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix


Cant make everyone happen...

**Comment by cartazio** [comment]
Dont mix brew and macports.  Also do t use brew GHC.  Use ghc for OSX app
